import { Library, ListVideo, Music2, Radio } from "lucide-react";
import type { Profile, TasteData } from "@/lib/types";
import { tasteDescription, tasteTitle, uniqueLabels } from "@/lib/taste";

interface TasteProfileCardProps {
  profile?: Profile;
  data?: TasteData;
  label: string;
  tone?: "lime" | "violet";
  compact?: boolean;
}

export const TasteProfileCard = ({ profile, data, label, tone = "lime", compact = false }: TasteProfileCardProps) => {
  const name = profile?.name || label;
  const firstName = name.split(" ")[0];
  const topics = uniqueLabels(data, compact ? 3 : 6);
  const metrics = [
    { label: "Channels", value: data?.subscriptions.length || 0, icon: Radio },
    { label: "Saved", value: data?.saved_videos.length || 0, icon: Library },
    { label: "Music", value: data?.music_listened.length || 0, icon: Music2 },
    { label: "Playlists", value: data?.playlists.length || 0, icon: ListVideo },
  ];

  return (
    <article className={`taste-profile-card taste-profile-${tone} ${compact ? "taste-profile-compact" : ""}`}>
      <header className="taste-profile-header">
        {profile?.picture ? <img src={profile.picture} alt={`${name}'s Google profile`} referrerPolicy="no-referrer" /> : <span>{firstName.slice(0, 1).toUpperCase()}</span>}
        <div><small>{label}</small><h3>{name}</h3>{profile?.email && !compact ? <p>{profile.email}</p> : null}</div>
      </header>
      <div className="taste-profile-story"><span>Blend profile</span><strong>{tasteTitle(data)}</strong><p>{tasteDescription(data)}</p></div>
      <dl className="taste-profile-metrics">
        {metrics.map(({ label: metricLabel, value, icon: Icon }) => <div key={metricLabel}><dt><Icon aria-hidden="true" />{metricLabel}</dt><dd>{value}</dd></div>)}
      </dl>
      <div className="taste-profile-topics" aria-label={`${firstName}'s broad interest labels`}>
        {topics.length ? topics.map((topic) => <span key={topic}>{topic}</span>) : <span>More signal after the next refresh</span>}
      </div>
      <p className="taste-profile-disclaimer">Profile title and description are generated by Blend from the counts above.</p>
    </article>
  );
};
